# Generated by Django 5.2.5 on 2025-08-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='Default message content'),
        ),
    ]
