# Generated by Django 5.2.5 on 2025-08-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_message_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepient',
            new_name='Recipient',
        ),
    ]
