# Generated by Django 5.2.5 on 2025-08-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_rename_recepient_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('SENT', 'Sent')], default='Pending', max_length=10),
        ),
    ]
