# Generated by Django 5.2.5 on 2025-08-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_recipient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
