# Generated by Django 5.2.5 on 2025-08-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_leader_phone_number_alter_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_to',
            field=models.ManyToManyField(related_name='messages', to='sms.leader'),
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
